server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location ~ ^/assets/ {
        try_files $uri =404;
        access_log off;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        include fastcgi_params;
    }

    location /storage/ {
        internal;
        alias /var/www/html/storage/;
    }

    client_max_body_size 10M;
}
